//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCF_TP
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillInfo
    {
        public int Id { get; set; }
        public int BillId { get; set; }
        public int MenuId { get; set; }
        public int Count { get; set; }
    
        public virtual Bill Bill { get; set; }
        public virtual Menu Menu { get; set; }
    }
}
